version: "3.6"

services:
  # Backend
  backend:
    image: backend
    build: ./backend
    environment:
      - WHATSAPP_APP_ID
      - WHATSAPP_API_TOKEN
      - OPENAI_API_KEY
    ports:
      - ${PORT}:8080
    restart: always

  # MongoDB
  mongo:
    image: "docker.io/library/mongo:6.0.3"
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db

volumes:
  # MongoDB Volumes
  mongodb_volume:
